[package]
name = "twisted"
version = "0.1.0"
authors = ["lePerdu <zdpeltzer@gmail.com>"]
edition = "2018"

[dependencies]
auto_ops = "0.1"
lazy_static = "1.4"
log = "0.4"
num-integer = "0.1"
num-derive = "0.3"
num-traits = "0.2"
strum = { version = "0.19", features = ["derive"] }
termion = "1.5"
